app: 
  image: "avramach/cmad-blog:staging"
  links:
    - "db:db"
  ports:
    - "9999:8080"
db:
  environment:
    - MYSQL_ROOT_PASSWORD=password
  image: "mysql:latest"
  ports:
    - "6606:3306"
  volumes:
    - /var/lib/mysql
